//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Codingame.Puzzle.SudokuValidator {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    public class TestCases {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal TestCases() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("Codingame.Puzzle.SudokuValidator.TestCases", typeof(TestCases).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        public static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 3 5 2 6 9 7 8 1
        ///6 8 2 5 7 1 4 9 3
        ///1 9 7 8 3 4 5 6 2
        ///8 2 6 1 9 5 3 4 7
        ///3 7 4 6 8 2 9 1 5
        ///9 5 1 7 4 3 6 2 8
        ///5 1 9 3 2 6 8 7 4
        ///2 4 8 9 5 7 1 3 6
        ///7 6 3 4 1 8 2 5 9.
        /// </summary>
        public static string AnotherCorrectGrid {
            get {
                return ResourceManager.GetString("AnotherCorrectGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 2 3 4 5 6 7 8 9
        ///4 5 6 7 8 9 1 2 3
        ///7 8 9 1 2 3 4 5 6
        ///9 1 2 3 4 5 6 7 8
        ///3 4 5 6 7 8 9 1 2
        ///6 7 8 9 1 2 3 4 5
        ///8 9 1 2 3 4 5 6 7
        ///2 3 4 5 6 7 8 9 1
        ///5 6 7 8 9 1 2 3 4.
        /// </summary>
        public static string BasicGrid {
            get {
                return ResourceManager.GetString("BasicGrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 3 5 2 6 9 7 8 1
        ///6 8 2 5 7 1 4 9 3
        ///1 9 7 8 3 4 5 6 2
        ///8 2 6 1 9 5 3 4 7
        ///3 7 4 6 8 2 9 1 5
        ///1 5 9 7 4 3 6 2 8
        ///5 1 9 3 2 6 8 7 4
        ///2 4 8 9 5 7 1 3 6
        ///7 6 3 4 1 8 2 5 9.
        /// </summary>
        public static string ColumnError {
            get {
                return ResourceManager.GetString("ColumnError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 3 2 2 6 9 7 8 1
        ///6 8 5 5 7 1 4 9 3
        ///1 9 7 8 3 4 5 6 2
        ///8 2 6 1 9 5 3 4 7
        ///3 7 4 6 8 2 9 1 5
        ///9 5 1 7 4 3 6 2 8
        ///5 1 9 3 2 6 8 7 4
        ///2 4 8 9 5 7 1 3 6
        ///7 6 3 4 1 8 2 5 9.
        /// </summary>
        public static string RowError {
            get {
                return ResourceManager.GetString("RowError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 5 9 6 1 4 2 5 3 7
        ///6 1 4 3 5 8 2 4 8
        ///5 6 9 4 1 2 5 3 6
        ///1 9 5 3 6 8 4 1 6
        ///5 9 3 6 3 4 8 2 1
        ///5 9 5 3 2 1 4 5 6
        ///1 3 6 4 8 6 5 2 5
        ///4 1 2 3 6 8 4 9 2
        ///3 6 8 7 4 1 5 6 3.
        /// </summary>
        public static string RubbishError {
            get {
                return ResourceManager.GetString("RubbishError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 4 3 5 2 6 9 7 8 1
        ///6 8 2 5 7 1 4 9 3
        ///8 9 7 1 3 4 5 6 2
        ///1 2 6 8 9 5 3 4 7
        ///3 7 4 6 8 2 9 1 5
        ///9 5 1 7 4 3 6 2 8
        ///5 1 9 3 2 6 8 7 4
        ///2 4 8 9 5 7 1 3 6
        ///7 6 3 4 1 8 2 5 9.
        /// </summary>
        public static string SubgridError {
            get {
                return ResourceManager.GetString("SubgridError", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to 1 3 3 4 5 6 7 7 9
        ///4 5 6 7 7 9 1 3 3
        ///7 7 9 1 3 3 4 5 6
        ///9 1 3 3 4 5 6 7 7
        ///3 4 5 6 7 7 9 1 3
        ///6 7 7 9 1 3 3 4 5
        ///7 9 1 3 3 4 5 6 7
        ///3 3 4 5 6 7 7 9 1
        ///5 6 7 7 9 1 3 3 4.
        /// </summary>
        public static string WhenSummingIsNotEnough {
            get {
                return ResourceManager.GetString("WhenSummingIsNotEnough", resourceCulture);
            }
        }
    }
}
